name: Update lists

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  build-lists:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Process and Merge Rule Lists
      run: |
        mkdir -p rules
        process_src() {
          curl -sLf "$1" | grep -v '^[[:space:]]*#' | grep -v '^[[:space:]]*$' || true
        }

        echo "Processing AI category..."
        (
          process_src "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Shadowrocket/OpenAI/OpenAI.list"
          process_src "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Shadowrocket/Claude/Claude.list"
          process_src "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Shadowrocket/Gemini/Gemini.list"
        ) | sort -u > rules/AI.list

        echo "Processing Media category..."
        (
          process_src "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Shadowrocket/Spotify/Spotify.list"
          process_src "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Shadowrocket/Netflix/Netflix.list"
          process_src "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Shadowrocket/TikTok/TikTok.list"
        ) | sort -u > rules/Media.list

        echo "Processing Work category..."
        (
          process_src "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Shadowrocket/Figma/Figma.list"
          process_src "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Shadowrocket/Adobe/Adobe.list"
          process_src "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Shadowrocket/Slack/Slack.list"
        ) | sort -u > rules/Work.list

        echo "Processing Gaming category..."
        (
          process_src "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Shadowrocket/PlayStation/PlayStation.list"
          process_src "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Xbox/Xbox.list"
        ) | sort -u > rules/Gaming.list

    - name: Commit and Push Changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        
        git add rules/
        
        if git diff --cached --quiet; then
          echo "No changes found. Everything is up to date."
        else
          git commit -m "Automated update"
          git push
        fi
